server:
  http:
    addr: 0.0.0.0:8112
    timeout: 1000s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:wang111000@tcp(127.0.0.1:3306)/new8?parseTime=true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  jwt_key: f33933ab18063c2e008115594b901f67 # md5 dhbmachine